# Generated by Django 5.0 on 2024-01-22 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_kryptos_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kryptos',
            name='CreatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
