# Generated by Django 5.0 on 2024-01-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Birthday',
        ),
    ]
