# Generated by Django 5.0 on 2024-01-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_user_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
