# Generated by Django 5.0 on 2024-02-13 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_expenses_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='KryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
