# Generated by Django 5.0 on 2024-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_kryptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kryptos',
            name='Worth',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
