# Generated by Django 5.0 on 2024-01-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_alter_kryptos_worth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finances',
        ),
        migrations.DeleteModel(
            name='Finanse',
        ),
    ]
